#!/bin/bash
# Signs a release archive with the Ed25519 update key, producing <archive>.sig.
#
# The key comes from $UPDATE_SIGNING_KEY (base64, as generated by
# scripts/generate-update-keys.sh). Exits 0 without signing when no key is set, so
# release builds work whether or not signing is configured.
#
#   UPDATE_SIGNING_KEY=… scripts/sign-update.sh dist/mySolat-1.0.0-universal.zip
set -euo pipefail

ARCHIVE="${1:?usage: sign-update.sh <archive>}"
[ -f "$ARCHIVE" ] || { echo "error: $ARCHIVE not found" >&2; exit 1; }

if [ -z "${UPDATE_SIGNING_KEY:-}" ]; then
  echo "· UPDATE_SIGNING_KEY not set — skipping signature (SHA-256 verification still applies)"
  exit 0
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

cat > "$WORK/sign.swift" <<'SWIFT'
import CryptoKit
import Foundation

// argv: <archive> ; key via UPDATE_SIGNING_KEY
guard let base64Key = ProcessInfo.processInfo.environment["UPDATE_SIGNING_KEY"],
      let keyData = Data(base64Encoded: base64Key.trimmingCharacters(in: .whitespacesAndNewlines))
else {
    FileHandle.standardError.write("error: UPDATE_SIGNING_KEY is not valid base64\n".data(using: .utf8)!)
    exit(1)
}

do {
    let key = try Curve25519.Signing.PrivateKey(rawRepresentation: keyData)
    let payload = try Data(contentsOf: URL(fileURLWithPath: CommandLine.arguments[1]))
    let signature = try key.signature(for: payload)
    print(signature.base64EncodedString())
} catch {
    FileHandle.standardError.write("error: \(error)\n".data(using: .utf8)!)
    exit(1)
}
SWIFT

swiftc -O -o "$WORK/sign" "$WORK/sign.swift"
"$WORK/sign" "$ARCHIVE" > "$ARCHIVE.sig"

echo "✓ $ARCHIVE.sig"
